"""Shared WeChat window geometry for local post-send capture."""

WECHAT_BUNDLE_ID = "com.tencent.xinWeChat"
WECHAT_COMPOSER_LEFT_POINTS = 305
WECHAT_COMPOSER_RIGHT_POINTS = 8
WECHAT_COMPOSER_TOP_POINTS = 146
WECHAT_CHAT_HEADER_POINTS = 64
